### PR TITLE
Fix to pass FIDO® EdDSA conformance tests

### PR DESCRIPTION
**Pull request by Littlelies**

### CODE REVIEW

**Comment by aseigler** [comment]
This used to work fine, did the conformance test change?  Related to https://github.com/fido-alliance/conformance-tools-issues/issues/495 possibly?

**Comment by Littlelies** [comment]
I can only say it works now on latest conformance test tools (v1.1.6, Sept 9th 2019)

**Comment by aseigler** [comment]
Sure enough. LGTM.

**Comment by nicksteele** [comment]
Thanks for the fix!

**Pull request merged**
