### PR TITLE
Extra test coverage for P-256 signature verification (webauthcose pkg)

### PR DESCRIPTION
**Pull request by ArnaudBrousseau**
For a few hours I was convinced that this library (`webauthncose` package specifically) wasn't doing its job properly because my code was accepting bad signatures as valid. So I set out to write a test to capture this. Turns out: this library is doing its job, and my code was at fault!

<details>
<summary>Shameful details</summary>
<pre>
func checkWebauthnSignature(...) error {
    valid, err := webauthncose.VerifySignature(key, message, sigBytes)
    if !valid || err != nil {
        return errors.Wrap(err, "error verifying signature")
    }
}
</pre>

The bug in the above snippet: `errors.Wrap(nil, "something")` is `nil`. Which means when `valid` is `false`, `nil` is returned 🤦 
</details>

Instead of discarding this test I thought it'd be a good addition to the test suite. The `go.mod` additions are a bonus, can definitely revert those if preferred.

### CODE REVIEW

**Comment by ArnaudBrousseau** [comment]
@james-d-elliott mind giving me a thumbs up to run the automated tests on this branch? I'm seeing "First-time contributors need a maintainer to approve running workflows".

**Comment by james-d-elliott** [comment]
I'm not one of the contributors but you should check out #155

**Comment by ArnaudBrousseau** [comment]
@james-d-elliott apologies for the confusion, and thanks for the link! I should close this PR and make a new one at https://github.com/go-webauthn/webauthn if I understand correctly?

**Comment by james-d-elliott** [comment]
The other issue is not set in stone at present but considering the maintainers and original author is supportive of such a move it may be worth at least making a new PR there in the interim.

I suspect there will be no further changes to this library that are not either documentation changes or patches to serious vulnerabilities in the unlikely instance they are discovered however I cannot speak authoritatively on this matter.

**Comment by ArnaudBrousseau** [comment]
Closing this one in favor of https://github.com/go-webauthn/webauthn/pull/72

**Pull request closed without merging**
