### PR TITLE
Fix TPMS_ECC_POINT parsing for TPM attestation with ECC key

### PR DESCRIPTION
**Pull request by aseigler**
- Add COSE elliptic curve constants
- Add map for COSE elliptic curve to TPM elliptic curve values
- Properly compare curve value from pubArea to curve from credentialPublicKey
- Add test for TPM attestation when ECC key is utilized

### CODE REVIEW

**Review by MasterKale — APPROVED** [review]
lgtm :shipit:

**Review by james-d-elliott — COMMENTED** [review]
LGTM. Though would it maybe be neater to add a receiver to webauthncose.EC2PublicKeyData which returns the TPM value?

**Comment by aseigler** [comment]
That's not a bad idea. I can't see why we could ever need to do that import. In fact, I am struggling to recall why I grabbed just the tiny pieces for googletpm instead of just importing the go-tpm package and using that.

**Comment by MasterKale** [comment]
@james-d-elliott Would you like to give the most recent changes a once-over and approve/review accordingly?

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Pull request merged**
