### PR TITLE
FIDO Server conformance tests now passing 100%

### PR DESCRIPTION
**Pull request by aseigler**
In order to pass the metadata tests and a small number of non-metadata tests, you must press the "DOWNLOAD SERVER METADATA" button in the conformance client and extract the resulting archive file into the folder referenced by this line: https://github.com/duo-labs/webauthn.io/blob/2c2c93545aeec2f9ce76c66834c3de4d2ec4adda/server/fido-conformance.go#L70

If you wish to use production metadata, you must obtain an access token from https://mds2.fidoalliance.org/tokens/ and put it in the environment variable referenced by this line: https://github.com/duo-labs/webauthn.io/blob/2c2c93545aeec2f9ce76c66834c3de4d2ec4adda/server/server.go#L109

If you wish to use custom metadata, for example https://github.com/solokeys/solo/blob/master/metadata/Solo-FIDO2-CTAP2-Authenticator.json, you would store that metadata file in a folder and load It like this line: https://github.com/duo-labs/webauthn.io/blob/2c2c93545aeec2f9ce76c66834c3de4d2ec4adda/server/server.go#L158

### CODE REVIEW

**Comment by aseigler** [comment]
IMG_20190501_172116

**Comment by nicksteele** [comment]
seeing what could be a unicode error in the test results here, gonna pull down the branch and see what's up

**Comment by aseigler** [comment]
If it's the 5th metadata test, you can just turn that one off for now. That test will still fail but the error will change pending https://github.com/fido-alliance/conformance-tools-issues/issues/438.

**Comment by nicksteele** [comment]
Great stuff

**Pull request merged**
