### PR TITLE
Securty Update for CVEs in JWT lib

### PR DESCRIPTION
**Pull request by HaBaLeS**
Move form JWT: https://github.com/dgrijalva/jwt-go to Community maintained clone https://github.com/dgrijalva/jwt-go for CVE's reported by Dependabot

### CODE REVIEW

**Comment by nklaassen** [comment]
> Move form JWT: https://github.com/dgrijalva/jwt-go to Community maintained clone https://github.com/dgrijalva/jwt-go for CVE's reported by Dependabot

Typo here, I think you mean that this PR switches from https://github.com/dgrijalva/jwt-go to the community maintained https://github.com/golang-jwt/jwt. Would like to see this merged so that we can continue to use this library without forking

**Comment by oschwald** [comment]
It would be great to see this merged so that we don't have to switch to a fork.

**Comment by james-d-elliott** [comment]
> It would be great to see this merged so that we don't have to switch to a fork.

For this particular fix you wouldn't need to. A replace on the affected downstream library will do it. Just add this to your go.mod:

replace github.com/dgrijalva/jwt-go => github.com/golang-jwt/jwt/v4 v4.2.0

**Comment by oschwald** [comment]
@james-d-elliott, thanks for mentioning that. I hadn't looked closely enough at the PR to realize that `golang-jwt` was completely compatible with `jwt-go`.

**Comment by james-d-elliott** [comment]
Yep github.com/golang-jwt/jwt is the "official" community fork of the original and the original is officially unmtaintained. See https://github.com/dgrijalva/jwt-go/issues/462 for more info. The main difference between v3 and v4 is that v3 didn't properly setup the module path (hence the `+incompatible` suffix); as well as the CVE fix.

**Comment by MasterKale** [comment]
I just got write access to this repo so I can at least merge PRs. I am _not_ in a position to actually review code beyond a PR like this so I'll be relying on feedback from @nicksteele and other maintainers to gauge which PR's are suitable to merge.

That said this PR seems fine to me. I'm considering merging this and closing #95 since this PR updates to a more recent version of `golang-jwt/jwt`. Any objections?

**Comment by james-d-elliott** [comment]
Yeah that seems like the best course of action in my opinion. For reference I'd rate #93 as the most important fix outstanding by the way. For reference this change updates a library for a CVE that actually doesn't affect this repos usage of the library, at least as far as I can tell.

**Pull request merged**
