### PR TITLE
Consolidate COSE things to their own area

### PR DESCRIPTION
**Pull request by aseigler**

### CODE REVIEW

**Comment by nicksteele** [comment]
@jordan-wright and I have looked at this and it LGTU. Thanks again!

**Comment by AGWA** [comment]
This pull request did more than just move code.  It also changed the implementation of `OKPPublicKeyData.Verify`.

The old code:

https://github.com/duo-labs/webauthn/blob/76dd83f95125fa95a9a48eb38f68f9bced646850/protocol/authenticator.go#L356-L362

The new code:

https://github.com/duo-labs/webauthn/blob/a18915cac5bac6aad627a83b2c35def1e7a6faa2/protocol/webauthncose/webauthncose.go#L60-L71

@aseigler, what was the rationale behind this change?

**Comment by aseigler** [comment]
I honestly don't recall specifically. It's obvious now that the old code would definitely be preferred if it actually works.

**Comment by jordan-wright** [comment]
Just a heads up, I have a PR that I will send up today which addresses #56 but in the process reimplements this part of the code.

**Pull request merged**
