### PR TITLE
Update webauthn.js

### PR DESCRIPTION
**Pull request by aseigler**
https://github.com/sweetalert2/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2

Seems that this library had a major breaking change which has broken WebAuthn.io demo site.  I believe this will fix it, worked for me.

### CODE REVIEW

**Comment by jordan-wright** [comment]
Hey @aseigler,

Thanks for sending this in! It looks like sweetalert2 definitely had some breaking changes a few days ago- great catch! This fix looks good to me.

Just to give a heads up, we're working to refactor a lot of this site in really exciting ways, so we'll make sure to carry these fixes over to the refactor as well. 😄 

Thanks again for getting in touch!

**Comment by aseigler** [comment]
Sure thing! We actually used your html and javascript in our demo project (https://github.com/abergs/fido2-net-lib/tree/master/Fido2Demo/wwwroot). I figured out the problem in our site and wanted to make sure you had the info as well. Will keep an eye out for the refactor!

**Comment by jordan-wright** [comment]
Morning @aseigler!

Just wanted to let you know that the refactor is live! You can find the new site here https://webauthn.io/. You'll notice a reference to your great .NET library there as well! 😄 

The updated code for the site itself is located here: https://github.com/duo-labs/webauthn.io

**Comment by aseigler** [comment]
Looks awesome!  Great work!

**Comment by aseigler** [comment]
Platform authenticator option doesn't seem to be working.

**Comment by jordan-wright** [comment]
Oh no! Thanks for the heads up!

I'm testing using Chrome on a Touchbar-enabled Mac and it seems to bring up TouchID to perform the operations and they complete successfully. Are there any details you can provide on your setup that might help us track down the root cause?

**Comment by aseigler** [comment]
So I tested with Chrome Canary on Android and it seems to work there, but specifically it did not work on Edge on Windows 10.  When I press the register button with platform selected, it does GET to makeCredential...and then nothing.  No error or anything.  Testing out a few other scenarios.

**Comment by jordan-wright** [comment]
That's perfect! Thanks for the heads up. I'll work to track down why Edge wasn't working and will push out a fix ASAP.

**Comment by aseigler** [comment]
So at first it looked like a repeat of #7 but I think there may be more to it.

**Pull request merged**
