### PR TITLE
Fix npe in test

### PR DESCRIPTION
**Pull request by 6543**
fix (partially) #91

----
if somebody do have the original `https://fidoalliance.co.nz/mds/pki/MDSROOT.crt` we could create a mockUp client

### CODE REVIEW

**Comment by aseigler** [comment]
> fix (partially) #91
> 
> # if somebody do have the original `https://fidoalliance.co.nz/mds/pki/MDSROOT.crt` we could create a mockUp client

Looked around but amazingly I don't find a cached copy.  That whole infrastructure got moved last year and the current test root is available at https://mds3.certinfra.fidoalliance.org/pki/MDS3ROOT.crt if it helps.

**Comment by james-d-elliott** [comment]
#100 talks about migration to mds v3. I think it would be a potentially beneficial to move to it. I think there are some elements that seem to be missing in v3 that existed in v2 like the revoke list though, maybe I'm mistaken just what it appeared like when I decoded the JWT; however without the mds v2 data it's a bit hard to validate that.

**Comment by aseigler** [comment]
Definitely need to move from MDS2 towards MDS3 in the next two calendar quarters. More than willing to help make this happen, MDS3 is far simpler than previous iterations.

**Comment by 6543** [comment]
I'm not too familiar with the underlaing protocoll/format jet ... I can write tests but the test files i can not generate myselve

**Comment by aseigler** [comment]
I have mostly completed migration to MDS3 and will send a PR soon which will make this obsolete. Suggest we close this one.

**Comment by 6543** [comment]
good to hear!

**Pull request closed without merging**
