### PR TITLE
Use CTAP2 canonical CBOR encoding form

### PR DESCRIPTION
**Pull request by Blobonat**
As stated in #78, currently the server accepts CBOR messages even if they do not follow the [CTAP2 canonical CBOR encoding form](https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#message-encoding). Therefore I added `webauthncbor/webauthncbor.go` which provides wrapper functions for [fxamacker/cbor](https://github.com/fxamacker/cbor) with encoding/decoding options following the CTAP2 canonical CBOR encoding form.

### CODE REVIEW

**Comment by MasterKale** [comment]
Hey @Blobonat I'm working to merge and/or close out currently outstanding PR's. There's a merge conflict blocking the merging of this one, if you still think this is worth merging can you fix the conflict while I chase down reviewers to give this a thumbs-up/thumbs-down?

**Comment by Blobonat** [comment]
@MasterKale Should be fixed now.

**Comment by MasterKale** [comment]
@Blobonat Thank you for dealing with the merge conflicts. I'll defer now to @nicksteele on the merge-ability of this PR.

**Review by aseigler — APPROVED** [review]
I am happy with this.

**Pull request merged**
